### ISSUE TITLE
Unhappy Path: Issues

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#10]
### Tasks
@beardofedu to review course: 12/17

- [ ] Review course, identify any issues and address each point below.
  - [ ] What happens when learner creates too many issues?
  - [ ] If learner unexpectedly closes issue, what happens?
- [ ] @hollenberry  to respond to reviews/code fixes: 12/18
