### ISSUE TITLE
Unhappy Path: Branches and PRs

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#11]
### Tasks
@beardofedu to review course: 12/17

- [ ] Review course, identify any issues and address each point below.
  - [ ] What if user creates wrong branch name?
  - [x] What if they create the wrong PR / wrong base: 
- [ ] @hollenberry  to respond to reviews/code fixes: 12/18
