### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#14]
PRP: @hectorsector

### Tasks
- [x] Figure out public launch date: Jan ~7th~ 9th, 2018
- [x] Submit updated permissions for LL on Prod (need read-only `Checks`) @JasonEtco with messaging:
  ```
  In order to support course content on Continuous Integration (CI), we need read-only permissions to checks reported by CI providers.
  ```
- [x] Flip CI with Circle course to public in prod.
- [x] Create a private CI with Travis course in prod.
- [x] Test private CI with Travis course. 
- [x] Flip CI with Travis course to public in prod.
- [x] Add CI courses to the internal list https://github.com/github/services-training/pull/947
