### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#15]
Based on [public launch date](https://github.com/githubtraining/ci/issues/14), write and determine social media dates.

### Tasks
- [ ] Assign dates below
- [x] Write Tweet: @hectorsector
- [ ] Write Blog (optional): @hectorsector
- [x] Move to editorial review: @carolynshin
- [ ] Incorporate an changes: @hectorsector

**Comment by hectorsector** [comment]
I believe this is a stale issue!
