### ISSUE TITLE
CI Project Plan

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#4]
@github/services-training :wave: Can you please review the following project plan? If something doesn't look quite right or if there is a bandwidth issue, please let me know! 

### Kick Off
- [x] Align on schedule, deadlines and PRPs: @carolynshin  (12/5)
  - [Project Board](https://github.com/githubtraining/ci/projects/1?add_cards_query=is%3Aopen)
- [x] Write Outline: @hectorsector (12/4)
- [x] Review Outline: @hollenberry  (12/4)
- [x] Decide on template code base: @ppremk  (12/5)
- [x] Create template repository: @ppremk (12/6) 

### Logic - Phase I
- [x] Write Config file with pseudocode: @hectorsector (12/4)
- [x] Write Readme - @hectorsector (12/4)
- [x] Review: @hollenberry  (12/5)
- [x] Open Issue for external Review of Readme: Marketing/@carolynshin (12/5)
- [x] Incorporate Readme feedback: @hollenberry  (12/14)
- [x] Gather list/reach out to SMEs/experts: @hollenberry (12/6 - 12/7)

### Bot Responses - Phase I
- [x] Create full response: @a-a-ron (~~12/6 - 7~~ 12/10 - 11) 
  - Revisions will happen through the end of the course

### Logic - Phase II
- [x] Get the config to a working state and push course to staging (use placeholder responses): @hectorsector (12/6)
- [x] Review course: @ppremk (12/7)
- [x] Respond to reviews/code fixes: @hectorsector  (12/10)

### Logic - Phase III
- [x] Review course:  @beardofedu (12/11 - 12/12)
- [x] Respond to reviews/Code Fixes: @hollenberry  12/13-14

### Bot Responses - Phase II
- [x] Check each response for valid links and images (open issues and fix via PR): @beardofedu (12/17)
- [x] Review PRs: @hollenberry (12/18)

### Testing
- [x] External hubbers to test course: @hollenberry (12/19)
- [x] Incorporate feedback received, if any: @hollenberry (12/20)
- [x] Finish Course: @hollenberry 12/21 (internal deadline)

### Deploy!
- [x] ???

### TO DO
- PRP: @hectorsector
- [x] Determine public ship date (December 21 OR January?)
- [x] Determine social media launch dates
  - [ ] Write Tweet
  - [ ] Write (optional) Blog
- [x] Team post to gather volunteers to test this course and future courses?
