### ISSUE TITLE
Course Readme

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#7]
### Tasks
- [x] Write Readme: @hectorsector
  - Link: https://github.com/githubtraining/ci/pull/2
  - Due: 12/4/18
- [x] Open issue for editorial review: @carolynshin
  - Link: https://github.com/github/marketing-content/issues/200
  - Due: 12/5/18
- [ ] Incorporate feedback from marketing: @hectorsector
  - Link: 
  - Due: 12/14/18 (or when they get back to us)
