### ISSUE TITLE
Template repository TODO 

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/ci-circle#75]
# Template Repository changes

### CircleCI config changes
- [x] TBD based on @ppremk's :sparkles: work

### Changing author
- [x] filter-base the template repo -> and we'll need to change line 167 of config to `right: "circle-ci: buildandtest"`

### Pull request template
- [x] Add PR template, title `.github/PULL_REQUEST_TEMPLATE`
  - [x] body:
    ```

    <!--This is a pull request template, and everything in these brackets won't appear when you open the pull request. They're comments.-->
    ### Change added

    - <!--Here, describe the changes you're introducing. In this pull request, you're introducing a configuration file for CircleCI.-->

    ```

### Extra merging taking extra time

Why is step merging master into custom build? That's what's taking a long time.

To avoid this, template repository `custom-build` branch should have `- image: circleci/ruby:2.4.1-node-browsers`. All branches except for initial-circle-config, `timestamp`, `master`, should have `- image: circleci/ruby:2.4.1-node-browsers`. `timestamp` doesn't matter.`add-links` should have it.
  - [x] Also, `add-links` should have `command: bundle exec jekyll build` on line 19. And, on this branch, `docs/01_getting_ready_for_class.md` should have body of:

```
---
layout: default
title: Getting ready for class
---

The time is: {{ site.time }}

## Getting Ready for Class
While you are waiting for class to begin, please take a few minutes to set up your local work environment.
```

- [x] Remove from config:
  - [x] line 95-98
    ```
        # # merge master in so we have config
      - type: mergeBranch
        head: master
        base: custom-build
    ```
  - [x] lines 209-212
    ```
        # merge master in so we have config
      - type: mergeBranch
        head: master
        base: add-links
    ```
