### ISSUE TITLE
Happy Path

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/ci-circle#9]
### Tasks
@ppremk to review course: 12/7

- [x] Review course, identify any issues and address each point below.
  - [x] Meets learning outcomes
  - [x] Meets level of complexity (not too easy or too difficult)
  - [x] Order of steps are appropriate
- [x] @hectorsector to respond to reviews/code fixes: 12/10
